
name: Checkout Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:


  CI:
    
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: build docker image node
        run:  docker build . --file Dockerfile --tag matantabachnik/final-python:${{ github.run_number }}-${{ github.sha }}

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASS }}

      - name: Push Docker image to Docker Hub
        run: docker push  matantabachnik/final-python:${{ github.run_number }}-${{ github.sha }}

     
